# Generated by Django 3.2.7 on 2021-11-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('regno', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('semester', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
