# Generated by Django 3.2.7 on 2021-11-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custName', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('desiredSquareFeet', models.FloatField()),
                ('needOfLoan', models.BooleanField()),
            ],
        ),
    ]
