# Generated by Django 3.2.7 on 2021-11-12 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cuid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone', models.PositiveIntegerField(null=True)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('placementTime', models.DateTimeField()),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demand.order')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demand.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demand.customer')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demand.order')),
            ],
        ),
    ]
